"""Framework-independent models shared by the RAG pipeline."""

from paper_research_copilot.domain.acquisition import (
    AcademicProvider,
    AcquisitionBudget,
    AcquisitionResult,
    AcquisitionRun,
    AcquisitionStatus,
    DownloadedPaper,
    DynamicIngestionResult,
    DynamicParseSummary,
    PaperAsset,
    PaperAssetStatus,
    PaperCandidate,
)
from paper_research_copilot.domain.answer import Answer
from paper_research_copilot.domain.corpus import (
    CorpusCatalog,
    CorpusManifestRecord,
    CorpusPaperAsset,
    CorpusPaperSpec,
    CorpusSpec,
)
from paper_research_copilot.domain.evidence import Citation, RetrievedChunk
from paper_research_copilot.domain.paper import (
    ChunkContext,
    IngestionSummary,
    PaperChunk,
    PaperMetadata,
    ParsedDocument,
    ParsedPage,
)
from paper_research_copilot.domain.parse import (
    DocumentParseResult,
    PageParseCandidate,
    PageParseResult,
    PageQualityFeatures,
    PageQualityResult,
    PageTextExtraction,
    ParseQualityStatus,
    ParserName,
    ParseRouteAction,
)
from paper_research_copilot.domain.structured_parse import (
    StructuredBlockType,
    StructuredContentBlock,
    StructuredPageResult,
    StructuredParseMethod,
)

__all__ = [
    "Answer",
    "AcademicProvider",
    "AcquisitionBudget",
    "AcquisitionResult",
    "AcquisitionRun",
    "AcquisitionStatus",
    "Citation",
    "ChunkContext",
    "CorpusCatalog",
    "CorpusManifestRecord",
    "CorpusPaperAsset",
    "CorpusPaperSpec",
    "CorpusSpec",
    "IngestionSummary",
    "DocumentParseResult",
    "DownloadedPaper",
    "DynamicIngestionResult",
    "DynamicParseSummary",
    "PageParseCandidate",
    "PageParseResult",
    "PageQualityFeatures",
    "PageQualityResult",
    "PageTextExtraction",
    "PaperChunk",
    "PaperAsset",
    "PaperAssetStatus",
    "PaperCandidate",
    "PaperMetadata",
    "ParsedDocument",
    "ParsedPage",
    "ParseQualityStatus",
    "ParseRouteAction",
    "ParserName",
    "RetrievedChunk",
    "StructuredBlockType",
    "StructuredContentBlock",
    "StructuredPageResult",
    "StructuredParseMethod",
]
